### ISSUE TITLE
Netflix not working

### ISSUE THREAD

**Issue by thexnetwork** [carlin-q-scott/browser-media-players#10]
Hey i recently just started using your addon on firefox and it works perfectly on websites like youtube but when i try on netflix nothing happens

**Comment by carlin-q-scott** [comment]
I don't have a Netflix account so I need someone to help with this feature request.

@thexnetwork can you follow the [instructions](https://github.com/carlin-q-scott/browser-media-players#capturing-player-control-elements) I just added to the readme for extracting the player controls from the Netflix player?

**Comment by thexnetwork** [comment]
It seems that it is a custom player as i cant right click on it and inspect element but some chrome extensions have made it work with netflix mabye you can find the controls there? 
I know its a long shot but here is a link the the popular Streamkeys addon
https://github.com/berrberr/streamkeys
Mabye it can help you. If needed i might be able to supply you with a netflix account if that dosnt work <3

**Comment by carlin-q-scott** [comment]
Thanks @thexnetwork . It looks like they're using the same locators that I'm using. 

Yesterday I pushed out an update that changed how the media button controls are interacted with, in order to fix support for plex.tv. Maybe that fix also worked on Netflix. Can you make sure you have version 2.1.4 and see if it's working?

Looking at StreamKeys, I'm wondering if I shouldn't just fork it and make it compatible with Firefox since it's also a WebExtension.

**Comment by thexnetwork** [comment]
I just attempted and sadly it dosnt work. If you need an account to test with dont hesistate to ask. And if you would be able to fork streamkeys then that sounds lovely, but its all up to you. One guy actually attempted that but sadly gave up after awhile and his also netflix dosnt work ;( and he dosnt support issues so i cant contact him. https://github.com/Egor3f/streamkeys-quantum . Due to firefox not allowing global hotkeys he created a seperate program. (everything can be found on the github)

**Comment by thexnetwork** [comment]
@carlin-q-scott ?

**Comment by carlin-q-scott** [comment]
Huh, I responded by email but it didn't go through.

Thanks for testing out the latest update. My housemate has a Netflix account so I can probably use his. I'll take a look again in a couple days with his account but if it's like the youtube player then I probably won't be able to do anything without API documentation provided by Netflix, which seems unlikely.

I'll take a look at streamkeys-quantum as it might help me provide a stop-gap for global hotkeys while the Firefox team adds support for them natively.

**Comment by carlin-q-scott** [comment]
Ok, I guess figuring out the API for the player control is much easier than I thought.

I can use this code to enumerate its methods: https://gist.github.com/carlin-q-scott/bdca8327460eb351c0a5f2b5bcb1d005

**Comment by thexnetwork** [comment]
Sounds lovely 👍

**Comment by thexnetwork** [comment]
@carlin-q-scott Hey not to be annoying or anything just wondering if there is an ETA on this. <3

**Comment by carlin-q-scott** [comment]
@thexnetwork I started working on this yesterday. Netflix did update their controls so this shouldn't take long.
