### ISSUE TITLE
Plex not working

### ISSUE THREAD

**Issue by FreekHelm** [carlin-q-scott/browser-media-players#12]
When playing a podcast in the plex web application (app.plex.tv) the media buttons don't work. YouTube works fine. Would be great to get this to work!

**Comment by carlin-q-scott** [comment]
This will take some time. Plex did work but they updated their UI and did something really unusual that I cannot figure out.

**Comment by carlin-q-scott** [comment]
This is the branch with updated xpaths. The click function and event aren't used by their new app written in ReactJS. From reading the source code I think I need to simulate a mouse click in its entirety.
