### ISSUE TITLE
New Deezer layout doesn't work

### ISSUE THREAD

**Issue by ghmv** [carlin-q-scott/browser-media-players#17]
The media keys don't work in the new Deezer.

Following your instructions, I found these buttons that unfortunately seems not to have any distinctive properties (aria-label is language dependent):

Play/Pause: `<button class="svg-icon-group-btn is-highlight" type="button" aria-label="Pauza"><svg class="svg-icon svg-icon-pause" focusable="false" height="1em" width="1em" viewBox="0 0 12 12" aria-hidden="true"><path d="M2.495 0h2.01C4.778 0 5 .224 5 .5v11a.5.5 0 0 1-.495.5h-2.01A.498.498 0 0 1 2 11.5V.5a.5.5 0 0 1 .495-.5zM7 .5a.5.5 0 0 1 .495-.5h2.01c.273 0 .495.224.495.5v11a.5.5 0 0 1-.495.5h-2.01A.498.498 0 0 1 7 11.5V.5z"></path></svg></button>`

Back: `<button class="svg-icon-group-btn" type="button" aria-label="Zpět"><svg class="svg-icon svg-icon-prev" focusable="false" height="1em" width="1em" viewBox="0 0 12 12" aria-hidden="true"><path d="M2 5.397V.5a.5.5 0 1 0-1 0v11a.5.5 0 1 0 1 0V6.597L11 12V0L2 5.397z"></path></svg></button>`

Next: `<button class="svg-icon-group-btn" type="button" aria-label="Další"><svg class="svg-icon svg-icon-next" focusable="false" height="1em" width="1em" viewBox="0 0 12 12" aria-hidden="true"><path d="M11 .5v11c0 .276-.232.5-.5.5a.503.503 0 0 1-.5-.5V7.08L1.562 11.95A.375.375 0 0 1 1 11.624V.376c0-.29.312-.47.562-.325L10 4.919V.5c0-.276.232-.5.5-.5.276 0 .5.229.5.5z"></path></svg></button>`

**Comment by carlin-q-scott** [comment]
@ghmv Thanks! You provided everything I needed to make it work.
