### ISSUE TITLE
Add method to manual set hotkey

### ISSUE THREAD

**Issue by cup** [carlin-q-scott/browser-media-players#2]
My keyboard at work does not have media buttons, so it would be nice if I could set the function keys
(F1-F12) or similar to act as media keys

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/86

**Comment by svnpenn** [comment]
https://github.com/randyrants/sharpkeys/issues/24

**Comment by carlin-q-scott** [comment]
Feature added a few months ago. I guess I forgot to close this. See the options page for the extension that's accessed from the about:addons page within Firefox.
