### ISSUE TITLE
Links to firefox bugs?

### ISSUE THREAD

**Issue by flying-sheep** [carlin-q-scott/browser-media-players#21]
Hi! The readme and description say that on firefox only play/pause work, and only when the browser window is active.

Could you please add links to bugzilla for the respective bugs in firefox?

**Comment by carlin-q-scott** [comment]
I added links to the two bugzilla issues in the Firefox exceptions paragraph of the readme with commit 41a2141ef177a5877477aa9bf5ab9dc1590e2db5

**Comment by flying-sheep** [comment]
Great, thank you!
