### ISSUE TITLE
Play/pause and stop not working correctly on Deezer in Firefox

### ISSUE THREAD

**Issue by ghmv** [carlin-q-scott/browser-media-players#31]
Hello.
Play/Pause doesn't pause playing but instead stops it. But then if pressing again, it doesn't start playing even from the first song of the album but in my case it plays a song from different album of the same musician (I don't understand how it could happen).

Stop instead pauses playing (but only pauses, it doesn't play again after pressing). Play/pause then can play again paused song. 

Just chaos. :)

FF DE 68.

Marek

**Comment by carlin-q-scott** [comment]
fixed in version 2.2.6 released today
