### ISSUE TITLE
Invalid controls for Yandex

### ISSUE THREAD

**Issue by zclimber** [carlin-q-scott/browser-media-players#39]
https://github.com/carlin-q-scott/browser-media-players/blob/d3fa7d39046e5284096c9093574da57e166c18ce/data/music.yandex.ru-view.js#L6-L9
New div classes for music.yandex.ru are the following:
Play - player-controls__btn deco-player-controls__button player-controls__btn_play
Pause - player-controls__btn deco-player-controls__button player-controls__btn_play player-controls__btn_pause
Next - player-controls__btn deco-player-controls__button player-controls__btn_next
Previous - player-controls__btn deco-player-controls__button player-controls__btn_prev

**Comment by carlin-q-scott** [comment]
Fixed with commit a06ad8f37e5a8687c15969d15e457825958cd4e4
