### ISSUE TITLE
Media Keys not Working on Plex (windows 10)

### ISSUE THREAD

**Issue by BreadJuice1** [carlin-q-scott/browser-media-players#41]
The extension works with youtube, but not on Plex, even after pinning the tab

**Comment by carlin-q-scott** [comment]
Are you using self-hosted Plex? If so, you need to go into extension settings for media keys and set the url for your plex installation.

Dec 4, 2019 12:02:52 AM BreadJuice1 <notifications@github.com>:

**Comment by BreadJuice1** [comment]
![image](https://user-images.githubusercontent.com/43072844/70192169-d20a2b80-16f2-11ea-85b1-de09ba672e85.png)

after setting the URL in the settings it still does not work, I am on Firefox Version 71.0 64 bit

**Comment by carlin-q-scott** [comment]
I'm looking into this but it was a long time since I last used my plex server so I had to run a bunch of updates before it was usable. I will hopefully check it tonight.

**Comment by carlin-q-scott** [comment]
@BreadJuice1 I believe this is fixed with the Saturday release of the extension. You will need to put **http://127.0.0.1/*** in the Plex configuration and save. It should work after that, assuming Firefox pulled down the update to v2.5.0
