### ISSUE TITLE
Yandex.Music support

### ISSUE THREAD

**Issue by isupovs** [carlin-q-scott/browser-media-players#44]
I'd like Yandex Music support to be added into the plugin.
1) **Link**: https://music.yandex.ru/ and https://music.yandex.com/
2) **Name**: Yandex Music
3) Play/Pause button:
```
<div class="d-icon d-icon_play"></div>
```
Prev button:
```
<div class="d-icon d-icon_track-prev"></div>
```
Next button:
```
<div class="d-icon d-icon_track-next"></div>
```

**Comment by carlin-q-scott** [comment]
@isupovs Did it start working?
