### ISSUE TITLE
doesnt work in chrome

### ISSUE THREAD

**Issue by schelkov** [carlin-q-scott/browser-media-players#7]
hello, i download this and install in chrome, first of all
1) "lib/browser-polyfill.min.js" manifest error
after editing (deleted this part of code) extension is installed but in does nothing. I opened Yandex Radio but media keys doesnt work. (opera same problem)

**Comment by carlin-q-scott** [comment]
That file is mandatory for Chrome support. After cloning this repo you need to run `npm install` to get it in the right place.

**Comment by schelkov** [comment]
how can i do that? i installed Node.js but what commands i have to write? is there video tut?

**Comment by carlin-q-scott** [comment]
In Windows while viewing a folder you can open Powershell into that folder via the "File" menu, like so:
![image](https://user-images.githubusercontent.com/2521644/47270745-fcb41780-d524-11e8-8e39-2b906886293b.png)
